name: Terraform CI for AWS-EKS Apply

permissions:
  id-token: write
  contents: read
on:
  push:
    branches:
      - main
    paths:
      - '**/*.tf'
      - '**/*.tfvars'
  pull_request:
    paths:
      - '**/*.tf'
      - '**/*.tfvars'
  workflow_dispatch: {}

env:
  TF_VAR_region: eu-west-2
  TF_VAR_profile: AdministratorAccess-803103365620

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production
    env:
      TF_DIR: EKS/EKS-Updated

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::803103365620:role/GitHubWorkFlowActions"
          aws-region: "eu-west-2"

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - name: Terraform Validate
        working-directory: ${{ env.TF_DIR }}
        run: terraform init -input=false && terraform validate

      - name: Terraform Plan
        id: plan
        working-directory: ${{ env.TF_DIR }}
        run: |
          set -o pipefail
          terraform plan -no-color -out=tfplan -input=false

      - name: Terraform Apply (Main Branch Only)
        working-directory: ${{ env.TF_DIR }}
        run: terraform apply tfplan
        continue-on-error: true
      - name: Commit and Push State File
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update terraform state [skip ci]"
          file_pattern: 'terraform.tfstate*'