name: Terraform CI for AWS EKS

permissions:
  id-token: write
  contents: read
on:
  push:
    branches:
      - main
    paths:
      - '**/*.tf'
      - '**/*.tfvars'
  pull_request:
    paths:
      - '**/*.tf'
      - '**/*.tfvars'
  workflow_dispatch: {}

env:
  TF_VAR_region: eu-west-2
  TF_VAR_profile: AdministratorAccess-803103365620

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::803103365620:role/GitHubWorkFlowActions # <-- Replace with your actual OIDC role ARN
          aws-region: ${{ env.TF_VAR_region }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        working-directory: ../../GitHub/Kubernetes-Winfo/Terraform/EKS-Updated

      - name: Terraform Init
        run: terraform init
        working-directory: ../../GitHub/Kubernetes-Winfo/Terraform/EKS-Updated

      - name: Terraform Validate
        run: terraform validate
        working-directory: ../../GitHub/Kubernetes-Winfo/Terraform/EKS-Updated

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -var-file="terraform.tfvars" -no-color -out=tfplan
          terraform show -no-color -no-declarations=false tfplan > plan.out
        working-directory: ../../GitHub/Kubernetes-Winfo/Terraform/EKS-Updated
        continue-on-error: true

      - name: Upload Plan as Artifact (PR Only)
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: ../../GitHub/Kubernetes-Winfo/Terraform/EKS-Updated/plan.out

      - name: Terraform Apply (Main Branch Only)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -var-file="terraform.tfvars"
        working-directory: ../../GitHub/Kubernetes-Winfo/Terraform/EKS-Updated
